### ISSUE TITLE
When using simhash for exact text search

### ISSUE THREAD

**Issue by Shellbye** [leonsim/simhash#24]
Well, in my case, I use simhash to search short text(twitter like), but not the keyword search, but the exact  text search. 

When the dataset is about 200,000, everything works fine, and it takes 0.01s to find the exact short text. But when dataset as about 20,000,000, there are so many `Big bucket found`, and it because slow and sometime did not return.

I think there are something i can do, after check some blogs, I rise k from 3 to 10, but it slow down even at small dataset. @leonsim recommend customized hash function, but I don't understand why and how.

**Comment by leonsim** [comment]
What do you mean by exact text search? Would you provide some use case demo code?

**Comment by Shellbye** [comment]
I think I should try more harder first, there are much more to check. Thank you anyway.
