### ISSUE TITLE
extensive logging

### ISSUE THREAD

**Issue by akellne** [leonsim/simhash#28]
It would be great, if the simhash module could use a custom logger. The advantage of this approach is that certain messages could be muted solely for the module, which is particularly useful, when using a couple of different modules that do extensive logging at the same time. 

```
log = logging.getLogger("simhash")

log.debug("my logging message")
```

**Comment by leonsim** [comment]
yes, can you make a pull request for that?

**Comment by akellne** [comment]
ok, I created a pull request for this issue. See #29

**Comment by leonsim** [comment]
commented. let's discuss this in #29 👍
