### ISSUE TITLE
Serialization and deserialization support

### ISSUE THREAD

**Issue by 731935354** [leonsim/simhash#32]
Hi,
There is no doubt that this project helps me a lot when I try to do deduplication on 130,000 wiki docs. However,  it makes me headache when I try to re-run the simhash building process even with multiprocessing.  Is there anyone who plan to add serialization and deserialization support in order to save time?

It seems that ZODB may be a proper backend tool.(Certainly I will have a try.)

**Comment by Piento28** [comment]
Hi,
I faced the problem of "ImportError: cannot import name 'Simhash'", but I suppose I install the package correctly...

**Comment by leonsim** [comment]
Thanks, Zhu. Have you tried out ZODB? How does it look like?
