### ISSUE TITLE
Equality operator for Simhash

### ISSUE THREAD

**Issue by arryon** [leonsim/simhash#35]
Hi,

Have you considered implementing the `__eq__` operator for the Simhash class, to compare two `.value()` values for two simhashes? That way a simhash is much more easily integrated into comparison flows like Python's unittests.

I could submit a PR if you're interested in this.

**Comment by leonsim** [comment]
That's a good idea, @arryon 👍

**Comment by leonsim** [comment]
The pull request has been merged. Closing this.
