### ISSUE TITLE
The Setting of F Parameters

### ISSUE THREAD

**Issue by yhfwww** [leonsim/simhash#38]
it is said parameter `f` is the dimensions of fingerprints.
How does the f parameter affect the hash value of the result？
I tried to compute the results of "abc" and "aaa", and found that the length was 64, and the other was 63.

![abc](https://user-images.githubusercontent.com/15652387/53556114-31447980-3b7e-11e9-97c6-77b66a5cb29b.PNG)

**Comment by leonsim** [comment]
@yhfwww the other is 63 because the leading bit is 0. Hope that helps you understand it.
