### ISSUE TITLE
ImportError: cannot import name 'Simhash'

### ISSUE THREAD

**Issue by wangwanyou** [leonsim/simhash#39]
[root@test simhash]# py
  Python 3.5.4 (default, Jul 10 2018, 23:55:37) 
  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> from simhash import Simhash
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: cannot import name 'Simhash'
  >>> import simhash
  >>> sh=simhash.Simhash()
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  AttributeError: module 'simhash' has no attribute 'Simhash'

**Comment by leonsim** [comment]
Maybe try to uninstall simhash and re-install? Are you installing some other library previously?

**Comment by hacker-lin** [comment]
you sure that  you  installed it   by   "pip install simhash"    ????

**Comment by annisun** [comment]
I have the same errors

![image](https://user-images.githubusercontent.com/26518100/63986406-68342180-cb06-11e9-973c-fb95e82694fd.png)

![image](https://user-images.githubusercontent.com/26518100/63986420-797d2e00-cb06-11e9-96c5-63bcdbb86ac9.png)

**Comment by annisun** [comment]
> Maybe try to uninstall simhash and re-install? Are you installing some other library previously?



> [root@test simhash]# py
> Python 3.5.4 (default, Jul 10 2018, 23:55:37)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from simhash import Simhash
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ImportError: cannot import name 'Simhash'
> > > > import simhash
> > > > sh=simhash.Simhash()
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > AttributeError: module 'simhash' has no attribute 'Simhash'


your python file running name is simhash.py?

**Comment by leonsim** [comment]
Yes, as @annisun said, please make sure the current folder doesn't contain a file with a name of `simhash.py`.
