### ISSUE TITLE
Simhash warning: Big Bucket Found

### ISSUE THREAD

**Issue by siddharthasandhu** [leonsim/simhash#4]
How does a bigger bucket effect the result in the code? Except for time does it effect the result?

**Comment by debunge** [comment]
Hello again, 

I'm constantly having "Big bucket found" warning. Performance  is very bad and playing with  parameter "f" does not seem to yield any results.
Basically I'm doing the following:
```
    for id, sh in result:
        if len(index.get_near_dups(sh)) > 0:
            nd += 1
            continue
        index.add(id, sh)
```

 I'm having 50k-60k texts which is not much, so I assume I'm doing something wrong as simhash must scale to google-large collections of texts, I assume from skimming the original paper. 

Can I do something, or re-write something? I would gladly push all improvements if my attempts of speeding it up to be fruitful.

**Comment by liangsun** [comment]
@debunge what kind of texts are you using? Different texts need different methods of generating the feature array.

**Comment by Shellbye** [comment]
How to avoid the `Big bucket found`?

**Comment by leonsim** [comment]
You have a lot of options depends on your situations. For example:
1. Choose a large `f` ( the dimensions of fingerprints)
2. Use a customized tokenizing method
3. Use a customized hashing function
etc

**Comment by Shellbye** [comment]
Thanks.

**Comment by Shellbye** [comment]
@leonsim , when you say customized hashing function, I don't understand why the default `_hashfunc` is not good enough. Will it hash different feature into same value? If I want to customized my own one, what shall I consider?

**Comment by leonsim** [comment]
@Shellbye hmm... it depends on your requirement... what's the category of texts are you trying to compare and how many texts do you have?

**Comment by leonsim** [comment]
@Shellbye would you open a new issue? because your topic is a little different of the current one.

**Comment by Shellbye** [comment]
@leonsim OK

**Comment by kootenpv** [comment]
@leonsim Could you give some example settings for a larger corpus? I believe 64 really assumes a small corpus as I tested with only 2000 strings and it already complained.

**Comment by leonsim** [comment]
64 is good according to http://www.wwwconference.org/www2007/papers/paper215.pdf

maybe you can optimise the hash function or feature list generation function.
