### ISSUE TITLE
Broken link in a comment

### ISSUE THREAD

**Issue by pajusmar** [leonsim/simhash#47]
Please replace broken reference to a pdf file in SimhashIndex.offsets

https://github.com/leonsim/simhash/blob/7337c9ae353dbdc32666e88ba07a75170c19b79c/simhash/__init__.py#L200

**Comment by leonsim** [comment]
Updated. Thanks for reporting.

**Comment by pajusmar** [comment]
Didn't notice it before but Readme file is also broken.

**Comment by leonsim** [comment]
Updated too. Thanks.
